In [1]:
# Age ->
'''
import sqlite3, csv
conn = sqlite3.connect("main.db")
cur = conn.cursor()
sql = """
CREATE TABLE Age_chart (
    Age_low INTEGER,
    Age_high INTEGER,
    Male INTEGER,
    Female INTEGER
    )
"""
cur.execute(sql)
count = 0
with open("Age_chart.csv", "r") as file:
    for row in file:
        #print(row)
        count += 1
        if count == 1:
            continue
        #print(row)
        cur.execute("INSERT INTO Age_chart VALUES (?,?,?,?)", row.split(","))
        conn.commit()
conn.close()
'''

OperationalError: table Age_chart already exists

In [6]:
# BP Chart 
'''
import sqlite3, csv
conn = sqlite3.connect("main.db")
cur = conn.cursor()
sql = """
CREATE TABLE BP_chart (
    Systolic_BP_low INTEGER,
    Systolic_BP_high INTEGER,
    Diastolic_BP_low INTEGER,
    Diastolic_BP_high INTEGER,
    Male INTEGER,
    Female INTEGER
    )
"""
cur.execute(sql)
count = 0
with open("BP_chart.csv", "r") as file:
    for row in file:
        #print(row)
        count += 1
        if count == 1:
            continue
        #print(row)
        cur.execute("INSERT INTO BP_chart VALUES (?,?,?,?,?,?)", row.split(","))
        conn.commit()
conn.close()
'''

In [7]:
# Diabetes
'''
import sqlite3, csv
conn = sqlite3.connect("main.db")
cur = conn.cursor()
sql = """
CREATE TABLE Diabetes_chart (
    Diabetes Text,
    Male INTEGER,
    Female INTEGER
    )
"""
cur.execute(sql)
count = 0
with open("Diabetes.csv", "r") as file:
    for row in file:
        #print(row)
        count += 1
        if count == 1:
            continue
        #print(row)
        cur.execute("INSERT INTO Diabetes_chart VALUES (?,?,?)", row.split(","))
        conn.commit()
conn.close()
'''

In [8]:
# Smoking
'''
import sqlite3, csv
conn = sqlite3.connect("main.db")
cur = conn.cursor()
sql = """
CREATE TABLE Smoking_chart (
    Smoking Text,
    Male INTEGER,
    Female INTEGER
    )
"""
cur.execute(sql)
count = 0
with open("Smoking.csv", "r") as file:
    for row in file:
        #print(row)
        count += 1
        if count == 1:
            continue
        #print(row)
        cur.execute("INSERT INTO Smoking_chart VALUES (?,?,?)", row.split(","))
        conn.commit()
conn.close()
'''

In [61]:
#GreekDataSet-2
'''
import sqlite3, csv
conn = sqlite3.connect("GreekDataSet-2.db")
cur = conn.cursor()
sql = """
CREATE TABLE GreekDataSetDB (
    Gender Text,
    Smoking Text,
    Age INTEGER,
    Systolic_BP INTEGER,
    TC INTEGER,
    Risk INTEGER
    )
"""
cur.execute(sql)
count = 0
with open("GreekDataSet-2.csv", "r") as file:
    for row in file:
        #print(row)
        count += 1
        if count == 1:
            continue
        #print(row)
        cur.execute("INSERT INTO GreekDataSetDB VALUES (?,?,?,?,?,?)", row.split(","))
        conn.commit()
conn.close()
'''

In [9]:
# HDL Cholesterol
'''
import sqlite3, csv
conn = sqlite3.connect("main.db")
cur = conn.cursor()
sql = """
CREATE TABLE HDLCholesterol_chart (
    HDL_low INTEGER,
    HDL_high INTEGER,
    Male INTEGER,
    Female INTEGER
    )
"""
cur.execute(sql)
count = 0
with open("HDL_cholesterol.csv", "r") as file:
    for row in file:
        #print(row)
        count += 1
        if count == 1:
            continue
        #print(row)
        cur.execute("INSERT INTO HDLCholesterol_chart VALUES (?,?,?,?)", row.split(","))
        conn.commit()
conn.close()
'''

In [10]:
# Points to score
'''
import sqlite3, csv
conn = sqlite3.connect("main.db")
cur = conn.cursor()
sql = """
CREATE TABLE PointsToScore_chart (
    TotalScore INTEGER,
    MaleRisk INTEGER,
    FemaleRisk INTEGER
    )
"""
cur.execute(sql)
count = 0
with open("points_to_score.csv", "r") as file:
    for row in file:
        #print(row)
        count += 1
        if count == 1:
            continue
        #print(row)
        cur.execute("INSERT INTO PointsToScore_chart VALUES (?,?,?)", row.split(","))
        conn.commit() 
conn.close()
'''

In [11]:
# Risk_category
'''
import sqlite3, csv
conn = sqlite3.connect("main.db")
cur = conn.cursor()
sql = """
CREATE TABLE RiskCategory_chart (
    Category TEXT,
    Risk_low INTEGER,
    Risk_high INTEGER
    )
"""
cur.execute(sql)
count = 0
with open("Risk_Category.csv", "r") as file:
    for row in file:
        #print(row)
        count += 1
        if count == 1:
            continue
        #print(row)
        cur.execute("INSERT INTO RiskCategory_chart VALUES (?,?,?)", row.split(","))
        conn.commit() 
conn.close()
'''

In [12]:
# total_cholesterol
'''
import sqlite3, csv
conn = sqlite3.connect("main.db")
cur = conn.cursor()
sql = """
CREATE TABLE TC_chart (
    Cholesterol_low INTEGER,
    Cholesterol_high INTEGER,
    Male INTEGER,
    Female INTEGER
    )
"""
cur.execute(sql)
count = 0
with open("total_cholesterol.csv", "r") as file:
    for row in file:
        #print(row)
        count += 1
        if count == 1:
            continue
        #print(row)
        cur.execute("INSERT INTO TC_chart VALUES (?,?,?,?)", row.split(","))
        conn.commit() 
conn.close()
'''

In [13]:
#GreekDataSet
'''
import sqlite3, csv
conn = sqlite3.connect("main.db")
cur = conn.cursor()
sql = """
CREATE TABLE GreekDataSet_chart (
    Gender Text,
    Smoking Text,
    Age_low INTEGER,
    Age_high INTEGER,
    Systolic_BP_low INTEGER,
    Systolic_BP_high INTEGER,
    TC_low INTEGER,
    TC_high INTEGER,
    Risk INTEGER
    )
"""
cur.execute(sql)
count = 0
with open("GreekDataSet.csv", "r") as file:
    for row in file:
        #print(row)
        count += 1
        if count == 1:
            continue
        #print(row)
        cur.execute("INSERT INTO GreekDataSet_chart VALUES (?,?,?,?,?,?,?,?,?)", row.split(","))
        conn.commit()
conn.close()
'''

In [19]:
# Suggestion
import sqlite3, csv
conn = sqlite3.connect("main.db")
cur = conn.cursor()
sql = """
CREATE TABLE Suggestion_chart (
    category Text,
    suggestion Text
    )
"""
#cur.execute(sql)
count = 0
with open("suggestion.csv", "r") as file:
    for row in file:
        #print(row)
        count += 1
        if count == 1:
            continue
        #print(row)
        cur.execute("INSERT INTO Suggestion_chart VALUES (?,?)", row.split(","))
        conn.commit()
conn.close()